# Site
title:              Project Hustle
bio:                ''
description:        ""
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:categories/:title"
    layout: post
    author:

# Jekyll
permalink:          /:categories/:title
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   ""

disqus:
  id:               ""     

# Social | Project Hustle
analytics-id:       "UA-118778501-1"
twitter: "heynehak"           
facebook: "neha778899"          
instagram: "heynehak"          
linkedin: "nehakul"             
youtubeUser:      
youtubeChannel: 
  
# personal
location:           San Francisco Bay Area, CA
phone:              Email me :P
email:              

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
